//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int UserInfoId { get; set; }
        public int ContactId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
